dist: precise
language: node_js
sudo: false
node_js:
  - 8
cache:
  directories:
  - node_modules
install:
  - npm install
script:
  - npm run lint
  - npm run test -- --coverage
after_success:
  - npm run coveralls
notifications:
  slack: 104corp:OjxdMag434HAo4es5ojIthBf